apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp-cont
        image: wordpress:6.5.4
        env:
          - name: WORDPRESS_DB_HOST
            value: db-svc
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_DATABASE
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "600Mi"
          limits:
            cpu: "250m"
            memory: "600Mi"
        volumeMounts:
        - name: wp-pv
          mountPath: /var/www/html
      volumes:
      - name: wp-pv
        persistentVolumeClaim:
          claimName: wp-pvc
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: mysql
spec:
  selector:
    app: wp
  ports:
    - name: http-wp
      port: 80
      nodePort: 30100
      targetPort: 80
  type: NodePort
