apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: mysql
type: Opaque
data:
  DB_USER: d3AtdXNlcg==
  MYSQL_ROOT_PASSWORD: Um9vdFBhc3M=
  DB_PASSWORD: V3BQYXNzd29yZA==
  DB_DATABASE: d3AtZGI=