apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data/mysql
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data/wp
  storageClassName: manual